let data = [
  {
    sort: 1,
    account_name: "isoftstoneit",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "北京",
    bigArea: "华北&华中",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-1-rebuild",
    config: true,
  },
  {
    sort: 2,
    account_name: "isoftstoneguangzhou",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "广州",
    bigArea: "华南",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-2-rebuild",
    config: true,
  },
  {
    sort: 3,
    account_name: "isoftstoneshanghai",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "上海",
    bigArea: "华东",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-3-rebuild",
    config: true,
  },
  {
    sort: 4,
    account_name: "isoftstonechengdu",
    ima_user_name: "louyongliang",
    ima_user_pwd: "Mc@000306",
    area: "四川",
    bigArea: "华南",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-4-rebuild",
    config: true,
  },
  {
    sort: 5,
    account_name: "isoftstone_si",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "湖北",
    bigArea: "华北&华中",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-5-rebuild",
    config: true,
  },
  {
    sort: 6,
    account_name: "ISS-XA-HWCloud",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "陕西",
    bigArea: "华北&华中",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-6-rebuild",
    config: true,
  },
  {
    sort: 7,
    account_name: "isoftstonehangzhou",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "浙江",
    bigArea: "华东",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-7-rebuild",
    config: true,
  },
  {
    sort: 8,
    account_name: "isoftstoneanhui",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "安徽",
    bigArea: "华东",
    areaLevel: "三类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-8-rebuild",
    config: true,
  },
  {
    sort: 9,
    account_name: "isoftstonejinan",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "山东",
    bigArea: "华东",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-9-rebuild",
    config: true,
  },
  {
    sort: 10,
    account_name: "isoftstoneguangxi",
    ima_user_name: "louyongliang",
    ima_user_pwd: "Mc@000306",
    area: "广西",
    bigArea: "西南",
    areaLevel: "三类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-10-rebuild",
    config: false,
  },
  {
    sort: 11,
    account_name: "isoftstonenanchang",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "江西",
    bigArea: "华东",
    areaLevel: "三类",
    canUse: 0, // 2021年使用，2022年启用新账号
    obsBacketName: "mag-hwcloud-sales-11-rebuild",
    config: true,
  },
  {
    sort: 12,
    account_name: "rtdl2020",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "江苏",
    bigArea: "华东",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-12-rebuild",
    config: true,
  },
  {
    sort: 13,
    account_name: "z01tcp_1",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "深圳",
    bigArea: "华南",
    areaLevel: "一类",
    canUse: 0, // 2021年使用，2022年启用新账号
    obsBacketName: "mag-hwcloud-sales-13-rebuild",
    config: true,
  },
  {
    sort: 14,
    account_name: "isoftstone-SZ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "深圳",
    bigArea: "华南",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-14-rebuild",
    config: true,
  },
  {
    sort: 15,
    account_name: "isoftstone-JX",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "江西",
    bigArea: "华东",
    areaLevel: "二类",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-15-rebuild",
    config: true,
  },
  {
    sort: 16,
    account_name: "isoftstone-FJ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "福建",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-16-rebuild",
    config: true,
  },
  {
    sort: 17,
    account_name: "isoftstone-CQ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "重庆",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-17-rebuild",
    config: true,
  },
  {
    sort: 18,
    account_name: "isoftstone-GZ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "贵州",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-18-rebuild",
    config: true,
  },
  {
    sort: 19,
    account_name: "isoftstone-YN",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "云南",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-19-rebuild",
    config: true,
  },
  {
    sort: 20,
    account_name: "isoftstone-HeB",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "河北",
    bigArea: "华北",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-20-rebuild",
    config: true,
  },
  {
    sort: 21,
    account_name: "isoftstone-HeN",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "河南",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-21-rebuild",
    config: true,
  },
  {
    sort: 22,
    account_name: "isoftstone-HuN",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "湖南",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-22-rebuild",
    config: true,
  },
  {
    sort: 23,
    account_name: "isoftstone-TJ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "天津",
    bigArea: "",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "mag-hwcloud-sales-23-rebuild",
    config: true,
  },
];

export default data;
