let data = [
  {
    sort: 24, // 接着已有的23个账号来
    account_name: "isoftstone-Go-GD",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "广州",
    bigArea: "华南",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },
  {
    sort: 25, // 接着已有的23个账号来
    account_name: "isoftstone-Go-BJ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "北京",
    bigArea: "华北",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 26,
    account_name: "isoftstone-Go-SH",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "上海",
    bigArea: "华东",
    areaLevel: "一类",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 27,
    account_name: "isoftstone-Go-ZJ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "浙江",
    bigArea: "华东",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 28,
    account_name: "isoftstone-Go-SX",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "陕西",
    bigArea: "华中",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 29,
    account_name: "isoftstone-Go-GX",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "广西",
    bigArea: "西南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 30,
    account_name: "isoftstone-Go-CQ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "重庆",
    bigArea: "西南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 31,
    account_name: "isoftstone-Go-SZ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "深圳",
    bigArea: "华南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 32,
    account_name: "isoftstone-Go-FJ",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "福建",
    bigArea: "华南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 33,
    account_name: "isoftstone-Go-JS",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "江苏",
    bigArea: "华东",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 34,
    account_name: "isoftstone-Go-HB",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "湖北",
    bigArea: "华中",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 35,
    account_name: "isoftstone-Go-SC",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "四川",
    bigArea: "西南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 36,
    account_name: "isoftstone-Go-HeN",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "河南",
    bigArea: "华中",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },

  {
    sort: 37,
    account_name: "isoftstone-Go-YN",
    ima_user_name: "isoftstone-yllouc",
    ima_user_pwd: "Mc@000306",
    area: "云南",
    bigArea: "西南",
    areaLevel: "",
    canUse: 1,
    obsBacketName: "",
    config: true,
  },
];

export default data;
